# These are supported funding model platforms

github: [username]
patreon: ubuntu-external-ssd-guide
open_collective: ubuntu-external-ssd-guide
ko_fi: ubuntu-external-ssd-guide
buy_me_a_coffee: ubuntu-external-ssd-guide
custom: ['https://example.com/donate']
